### ISSUE TITLE
Reposting Issue #1 from ansible-dachs

### ISSUE THREAD

**Issue by PipGrylls** [gavodachs/dachs-doc#18]
Original Issue:
https://github.com/gavodachs/ansible-dachs/issues/1

During testing on Debian 11 using ansible-dachs the following error is thrown:
```
TASK [load-data : Import Data] ************************************************************************************************************
failed: [192.168.98.130] (item=dachs imp) => {"ansible_loop_var": "loop_item", "changed": true, "cmd": ["dachs", "imp", "arihip", "q"], "delta": "0:00:00.810755", "end": "2022-03-08 17:43:06.372715", "loop_item": "dachs imp", "msg": "non-zero return code", "rc": 1, "start": "2022-03-08 17:43:05.561960", "stderr": "*** Error: Resource descriptor 'arihip' could not be located in file\nsystem", "stderr_lines": ["*** Error: Resource descriptor 'arihip' could not be located in file", "system"], "stdout": "", "stdout_lines": []}
failed: [192.168.98.130] (item=dachs limits) => {"ansible_loop_var": "loop_item", "changed": true, "cmd": ["dachs", "limits", "arihip", "q"], "delta": "0:00:00.835261", "end": "2022-03-08 17:43:07.522483", "loop_item": "dachs limits", "msg": "non-zero return code", "rc": 2, "start": "2022-03-08 17:43:06.687222", "stderr": "usage: dachs limits [-h] [-t] itemId\ndachs limits: error: unrecognized arguments: q", "stderr_lines": ["usage: dachs limits [-h] [-t] itemId", "dachs limits: error: unrecognized arguments: q"], "stdout": "", "stdout_lines": []}
```

Which can be generated directly from the command line :

```
dachsroot@debian11:/var/gavo/inputs/arihip$ dachs limits q
*X*X* Uncaught exception at toplevel
*** Error: Oops.  Unhandled exception AttributeError.

Exception payload: module 'gavo.utils' has no attribute
'pyparsingWhitechars'
```

Any suggestions on what may be happening here?

**Comment by PipGrylls** [comment]
The PR patches this issue to link in the tutorial. Updating the Debian package repository to DaCHSv2.4 would be preferable.

**Comment by msdemlei** [comment]
On Tue, Mar 08, 2022 at 09:46:24AM -0800, Philip Grylls wrote:
> ```
> ***@***.***:/var/gavo/inputs/arihip$ dachs limits q
> *X*X* Uncaught exception at toplevel
> *** Error: Oops.  Unhandled exception AttributeError.
> 
> Exception payload: module 'gavo.utils' has no attribute
> 'pyparsingWhitechars'
> ```
> 
> Any suggestions on what may be happening here?

That's a bug in the DaCHS 2.3 package as it sits in bullseye (I've
tried to sneak in an update by first getting a backport in, but it's
tough going).  A bit more on this is in the common problems document:
<http://docs.g-vo.org/DaCHS/commonproblems.html#module-gavo-utils-has-no-attribute-pyparsingwhitechars>,
and footnote 4 in the tutorial warns against it
(<http://docs.g-vo.org/DaCHS/tutorial.html#belim>).

Sorry about this.

An immediate fix would be to go back to our stable repo
<http://soft.g-vo.org/repo> -- or to simply not run dachs limits,
which is rather new anyway, and its effects are not picked up widely
by VO clients yet.
